version: 1
defaults:
  platform: github
  base_url: https://oss.open-digger.cn
  cache_dir: data/cache
  sqlite_path: data/sqlite/opendigger.db
repos:
- org: X-lab2017
  repo: open-digger
- org: apache
  repo: iotdb
- org: dataease
  repo: DataEase
- org: easy-graph
  repo: Easy-Graph
- org: iaurg
  repo: rocketseatdevs
- org: umrover
  repo: mrover-workspace
- org: Ada-C11
  repo: hash-practice
- org: JoseChaconUrias
  repo: GroceryStore
- org: atomiks
  repo: tippyjs-react
- org: node-honeycomb
  repo: node-honeycomb.github.io
- org: mhornstein
  repo: Glitters1
- org: JonYoung-dev
  repo: andromeda-agile-site
- org: IU3Labs
  repo: ToP_2025
- org: DataDog
  repo: swift-dogstatsd
- org: Dwit-Tech
  repo: core-banking-service
- org: Eugeshakw
  repo: water-tracker
- org: superluis1994
  repo: IAmed
- org: conda-forge
  repo: aenum-feedstock
- org: return42
  repo: searxng
- org: annsh4
  repo: module2ASD
- org: jenkinsci
  repo: export-job-parameters-plugin
- org: JustTemmie
  repo: steam-presence
- org: anitabaron
  repo: cinemania-goit
- org: Actindo-AG
  repo: Documentation
- org: kaltura
  repo: chromeless-kdp
- org: hol16046
  repo: wdd430_group
- org: FirelyTeam
  repo: firely-docs-firely-server
- org: GoogleCloudPlatform
  repo: gke-poc-toolkit
- org: hpi-swa-teaching
  repo: SWT18-Project-04
- org: gamerson
  repo: liferay-intellij-plugin
- org: ZimbraOS
  repo: zm-docker
- org: Topshelf
  repo: Topshelf
- org: EngineerFocus
  repo: FocusPro
- org: facebookresearch
  repo: blt
- org: hackclub
  repo: assemble-preflight-web
- org: open-telemetry
  repo: opentelemetry-js-contrib
- org: DankIdeaCentral
  repo: migrate-app
- org: gnosis
  repo: dx-services
- org: teamtype
  repo: teamtype
- org: eslint
  repo: eslintrc
- org: ratchetphp
  repo: Ratchet
- org: brave
  repo: googleads-referral
- org: mdaus
  repo: nitro
- org: CSE2024-SDP-Team5
  repo: thu-space-invaders
- org: Neautrino
  repo: python-questions
- org: gudaoxuri
  repo: dew
- org: GDG-ADGIPS
  repo: Hack-Chill-2.0
- org: jfrog
  repo: fly-action
- org: chatbot-devplus
  repo: employee-project-tracker
- org: droibit
  repo: flutter_custom_tabs
- org: hashicorp
  repo: terraform-foundational-policies-library
- org: conda-forge
  repo: forte2-feedstock
- org: jenkinsci
  repo: spotinst-plugin
- org: DP2-c2-028
  repo: Acme-SF-D04
- org: trustimaging
  repo: stride
- org: microsoft
  repo: rural-crowdsourcing-toolkit
- org: w3c
  repo: microdata
- org: littlejohn19
  repo: TAI_Lab_1
- org: CarlosMontano2005
  repo: BEST_PLAYER_2024
- org: rizafahmi
  repo: awesome-speakers-id
- org: grafana
  repo: otel-operator-demo
- org: WSU-4110
  repo: Able
- org: KW-GIRIGIRI
  repo: kw-rental-backend
- org: cloudflare
  repo: webcm-docs
- org: carrot
  repo: roots-contentful
- org: StatisticsGreenland
  repo: pxmake
- org: MasseyHackers
  repo: mh-githubs
- org: searchlight
  repo: searchlight
- org: tripledes
  repo: thesheriff
- org: bmax121
  repo: KernelPatch
- org: tomasbedrich
  repo: home-assistant-hikconnect
- org: al-fajri
  repo: pre-course
- org: DorinGI
  repo: event_booster_team_4
- org: Shuriken-Group
  repo: Shuriken-Analyzer
- org: skabanets
  repo: function-force
- org: 33-ohoh
  repo: 33-ohoh
- org: aws-cloudformation
  repo: iac-model-evaluation
- org: puppetlabs
  repo: install-puppet
- org: magento
  repo: tmp-pr-test1
- org: stackabletech
  repo: stackablectl
- org: microsoft
  repo: tim-data-investigate-platform
- org: prime-team-aeon
  repo: home-survey
- org: castorm
  repo: kafka-connect-http
- org: lovehackintosh
  repo: lede
- org: Cerebellum-Network
  repo: grant-program
- org: digicatapult
  repo: morello-ui
- org: sfuosdev
  repo: swe-resume-evaluator
- org: sailro
  repo: EscapeFromTarkov-Trainer
- org: ngaly277
  repo: zoo-management
- org: conda-forge
  repo: tensorflow-feedstock
- org: souravDgraph
  repo: Automation
- org: Mole1803
  repo: SPoRT
- org: twitterdev
  repo: twitter-leaderboard
- org: rancher
  repo: refpolicy
- org: illyasviel
  repo: crowds
- org: dinamio
  repo: hillel-javaee
- org: cta-observatory
  repo: magic-cta-pipe
- org: MetaMask
  repo: types
- org: Mentoring-Bordeaux
  repo: AutonomousCars
- org: UnBArqDsw2024-2
  repo: 2024.2_G10_Recomendacao_Entrega_01
- org: wonipapa
  repo: epg2xml
- org: awslabs
  repo: yesiscan
- org: welfoz
  repo: Machi_Koro
- org: yoav-zibin
  repo: GameBuilder
- org: ACINQ
  repo: phoenixd
- org: Alla-java
  repo: ADS-online
- org: Seol-Munhyeok
  repo: coby
- org: choojs
  repo: choo
- org: SWIFTSIM
  repo: pipeline-configs
- org: KryoEM
  repo: relion2
- org: Desarrollo-PI
  repo: Proyecto-Videojuego-SB
- org: omegapointnorge
  repo: omega-office-booking
- org: dart-lang
  repo: observe
- org: Hexa-Coders-aug23
  repo: product_catalog
- org: UMC-WEGO
  repo: WEGO_FE_React
- org: XX-net
  repo: XX-Net
- org: falcosecurity
  repo: cncf-green-review-testing
- org: GreenUniversityComputerClub
  repo: gucc
- org: AgoraIO
  repo: Basic-Video-Call
- org: DataBiosphere
  repo: data-explorer-indexers
- org: Ionaru
  repo: easy-markdown-editor
- org: stackrox
  repo: mishas-operator-index-fork
- org: learn-co-students
  repo: moving-things-with-javascript-bootcamp-prep-000
- org: MyResonance
  repo: tickets
- org: conda-forge
  repo: webtest-feedstock
- org: m3ntorship
  repo: m3ntorship.com
- org: thecasualcoder
  repo: tztail
- org: coding-blocks
  repo: hackerblocks.projectx
- org: mopub
  repo: mopub-android-sdk
- org: davidvida
  repo: js-reactjs-course
- org: heyitsmdr
  repo: armeria
- org: taikoxyz
  repo: taiko-client
- org: aternosorg
  repo: modbot
- org: encisosystems
  repo: set-web
- org: muhandojeon
  repo: Why-Do-We-Work
- org: QUACK-INTEC
  repo: memo-app
- org: wooncloud
  repo: animalcare
- org: laravel
  repo: nova-issues
- org: archesproject
  repo: arches-querysets
- org: alipay
  repo: quic-lb
- org: zencomputersystems
  repo: CMS_Analyst
- org: babelfish-for-postgresql
  repo: postgresql_modified_for_babelfish
- org: Pennebaker
  repo: craft-architect
- org: elixir-lang
  repo: highlight.js
- org: TeCOS-NIT-Trichy
  repo: first-issue-demo
- org: coroo
  repo: nova-chartjs
- org: JamesCJ60
  repo: Universal-x86-Tuning-Utility
- org: schibsted
  repo: account-sdk-android-web
- org: ohirofumi
  repo: freemarket_sample_54a
- org: ladieslearningcode
  repo: llc-intro-to-python
- org: ghscr
  repo: ghscription
  enabled: true
- org: llvm
  repo: llvm-project
  enabled: true
- org: NixOS
  repo: nixpkgs
  enabled: true
- org: 7Sence
  repo: Rise-Beta
  enabled: true
- org: CypherV2
  repo: Donarev-API
  enabled: true
- org: DXVVAY
  repo: hcaptcha-reverse
  enabled: true
- org: CSolverV2
  repo: hCaptcha-ID-Decoder
  enabled: true
- org: Expensify
  repo: App
  enabled: true
  registered_at: 2026-01-13T11:56:50.323Z
- org: sgl-project
  repo: sglang
  enabled: true
  registered_at: 2026-01-13T11:56:51.139Z
- org: taozhiyu
  repo: TyProAction
  enabled: true
  registered_at: 2026-01-13T12:03:15.802Z
- org: emrovsky
  repo: x-ms-reference-id
  enabled: true
  registered_at: 2026-01-13T14:00:15.621Z
- org: emrovsky
  repo: hcaptcha-blob-encryption
  enabled: true
  registered_at: 2026-01-13T14:38:27.892Z
- org: microsoft
  repo: vscode
  enabled: true
  registered_at: 2026-01-13T15:56:54.641Z
- org: pytorch
  repo: pytorch
  enabled: true
  registered_at: 2026-01-13T15:56:56.192Z
- org: anthropics
  repo: claude-code
  enabled: true
  registered_at: 2026-01-13T16:01:25.566Z
